ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "studentId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "groupe" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "interestsJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "volunteer" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "message" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rgpdAcceptedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "statutsAcceptedAt" TIMESTAMP(3);
