ALTER TABLE "Event" ADD COLUMN "programJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Event" ADD COLUMN "access" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Event" ADD COLUMN "practicalJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "Event" ADD COLUMN "customSectionsJson" TEXT NOT NULL DEFAULT '[]';
