/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AdhererRouteImport } from './routes/adherer'
import { Route as BdeRouteImport } from './routes/bde'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as BureauRouteImport } from './routes/bureau'
import { Route as ConditionsVenteRouteImport } from './routes/conditions-vente'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as RemboursementsRouteImport } from './routes/remboursements'
import { Route as BdeIndexRouteImport } from './routes/bde.index'
import { Route as BdeAssociationRouteImport } from './routes/bde.association'
import { Route as BdeEquipeRouteImport } from './routes/bde.equipe'
import { Route as BdePolesRouteImport } from './routes/bde.poles'
import { Route as BureauIndexRouteImport } from './routes/bureau.index'
import { Route as BureauDossierIdRouteImport } from './routes/bureau.$dossierId'
import { Route as EvenementsIndexRouteImport } from './routes/evenements.index'
import { Route as EvenementsEventIdRouteImport } from './routes/evenements.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhererRoute = AdhererRouteImport.update({
  id: '/adherer',
  path: '/adherer',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeRoute = BdeRouteImport.update({
  id: '/bde',
  path: '/bde',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauRoute = BureauRouteImport.update({
  id: '/bureau',
  path: '/bureau',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsVenteRoute = ConditionsVenteRouteImport.update({
  id: '/conditions-vente',
  path: '/conditions-vente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const RemboursementsRoute = RemboursementsRouteImport.update({
  id: '/remboursements',
  path: '/remboursements',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeIndexRoute = BdeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdeRoute,
} as any)
const BdeAssociationRoute = BdeAssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => BdeRoute,
} as any)
const BdeEquipeRoute = BdeEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => BdeRoute,
} as any)
const BdePolesRoute = BdePolesRouteImport.update({
  id: '/poles',
  path: '/poles',
  getParentRoute: () => BdeRoute,
} as any)
const BureauIndexRoute = BureauIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BureauRoute,
} as any)
const BureauDossierIdRoute = BureauDossierIdRouteImport.update({
  id: '/$dossierId',
  path: '/$dossierId',
  getParentRoute: () => BureauRoute,
} as any)
const EvenementsIndexRoute = EvenementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvenementsRoute,
} as any)
const EvenementsEventIdRoute = EvenementsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EvenementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/adherer': typeof AdhererRoute
  '/bde': typeof BdeRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/bureau': typeof BureauRouteWithChildren
  '/conditions-vente': typeof ConditionsVenteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/espace': typeof EspaceRoute
  '/evenements': typeof EvenementsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/remboursements': typeof RemboursementsRoute
  '/bde/association': typeof BdeAssociationRoute
  '/bde/equipe': typeof BdeEquipeRoute
  '/bde/poles': typeof BdePolesRoute
  '/bureau/$dossierId': typeof BureauDossierIdRoute
  '/evenements/$eventId': typeof EvenementsEventIdRoute
  '/bde/': typeof BdeIndexRoute
  '/bureau/': typeof BureauIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/adherer': typeof AdhererRoute
  '/boutique': typeof BoutiqueRoute
  '/conditions-vente': typeof ConditionsVenteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/espace': typeof EspaceRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/remboursements': typeof RemboursementsRoute
  '/bde/association': typeof BdeAssociationRoute
  '/bde/equipe': typeof BdeEquipeRoute
  '/bde/poles': typeof BdePolesRoute
  '/bureau/$dossierId': typeof BureauDossierIdRoute
  '/evenements/$eventId': typeof EvenementsEventIdRoute
  '/bde': typeof BdeIndexRoute
  '/bureau': typeof BureauIndexRoute
  '/evenements': typeof EvenementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/adherer': typeof AdhererRoute
  '/bde': typeof BdeRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/bureau': typeof BureauRouteWithChildren
  '/conditions-vente': typeof ConditionsVenteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/espace': typeof EspaceRoute
  '/evenements': typeof EvenementsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/remboursements': typeof RemboursementsRoute
  '/bde/association': typeof BdeAssociationRoute
  '/bde/equipe': typeof BdeEquipeRoute
  '/bde/poles': typeof BdePolesRoute
  '/bureau/$dossierId': typeof BureauDossierIdRoute
  '/evenements/$eventId': typeof EvenementsEventIdRoute
  '/bde/': typeof BdeIndexRoute
  '/bureau/': typeof BureauIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/adherer'
    | '/bde'
    | '/boutique'
    | '/bureau'
    | '/conditions-vente'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/espace'
    | '/evenements'
    | '/mentions-legales'
    | '/remboursements'
    | '/bde/association'
    | '/bde/equipe'
    | '/bde/poles'
    | '/bureau/$dossierId'
    | '/evenements/$eventId'
    | '/bde/'
    | '/bureau/'
    | '/evenements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/adherer'
    | '/boutique'
    | '/conditions-vente'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/espace'
    | '/mentions-legales'
    | '/remboursements'
    | '/bde/association'
    | '/bde/equipe'
    | '/bde/poles'
    | '/bureau/$dossierId'
    | '/evenements/$eventId'
    | '/bde'
    | '/bureau'
    | '/evenements'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/adherer'
    | '/bde'
    | '/boutique'
    | '/bureau'
    | '/conditions-vente'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/espace'
    | '/evenements'
    | '/mentions-legales'
    | '/remboursements'
    | '/bde/association'
    | '/bde/equipe'
    | '/bde/poles'
    | '/bureau/$dossierId'
    | '/evenements/$eventId'
    | '/bde/'
    | '/bureau/'
    | '/evenements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AdhererRoute: typeof AdhererRoute
  BdeRoute: typeof BdeRouteWithChildren
  BoutiqueRoute: typeof BoutiqueRoute
  BureauRoute: typeof BureauRouteWithChildren
  ConditionsVenteRoute: typeof ConditionsVenteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  EspaceRoute: typeof EspaceRoute
  EvenementsRoute: typeof EvenementsRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RemboursementsRoute: typeof RemboursementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adherer': {
      id: '/adherer'
      path: '/adherer'
      fullPath: '/adherer'
      preLoaderRoute: typeof AdhererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde': {
      id: '/bde'
      path: '/bde'
      fullPath: '/bde'
      preLoaderRoute: typeof BdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bureau': {
      id: '/bureau'
      path: '/bureau'
      fullPath: '/bureau'
      preLoaderRoute: typeof BureauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-vente': {
      id: '/conditions-vente'
      path: '/conditions-vente'
      fullPath: '/conditions-vente'
      preLoaderRoute: typeof ConditionsVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remboursements': {
      id: '/remboursements'
      path: '/remboursements'
      fullPath: '/remboursements'
      preLoaderRoute: typeof RemboursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/': {
      id: '/bde/'
      path: '/'
      fullPath: '/bde/'
      preLoaderRoute: typeof BdeIndexRouteImport
      parentRoute: typeof BdeRoute
    }
    '/bde/association': {
      id: '/bde/association'
      path: '/association'
      fullPath: '/bde/association'
      preLoaderRoute: typeof BdeAssociationRouteImport
      parentRoute: typeof BdeRoute
    }
    '/bde/equipe': {
      id: '/bde/equipe'
      path: '/equipe'
      fullPath: '/bde/equipe'
      preLoaderRoute: typeof BdeEquipeRouteImport
      parentRoute: typeof BdeRoute
    }
    '/bde/poles': {
      id: '/bde/poles'
      path: '/poles'
      fullPath: '/bde/poles'
      preLoaderRoute: typeof BdePolesRouteImport
      parentRoute: typeof BdeRoute
    }
    '/bureau/': {
      id: '/bureau/'
      path: '/'
      fullPath: '/bureau/'
      preLoaderRoute: typeof BureauIndexRouteImport
      parentRoute: typeof BureauRoute
    }
    '/bureau/$dossierId': {
      id: '/bureau/$dossierId'
      path: '/$dossierId'
      fullPath: '/bureau/$dossierId'
      preLoaderRoute: typeof BureauDossierIdRouteImport
      parentRoute: typeof BureauRoute
    }
    '/evenements/': {
      id: '/evenements/'
      path: '/'
      fullPath: '/evenements/'
      preLoaderRoute: typeof EvenementsIndexRouteImport
      parentRoute: typeof EvenementsRoute
    }
    '/evenements/$eventId': {
      id: '/evenements/$eventId'
      path: '/$eventId'
      fullPath: '/evenements/$eventId'
      preLoaderRoute: typeof EvenementsEventIdRouteImport
      parentRoute: typeof EvenementsRoute
    }
  }
}

interface BdeRouteChildren {
  BdeAssociationRoute: typeof BdeAssociationRoute
  BdeEquipeRoute: typeof BdeEquipeRoute
  BdePolesRoute: typeof BdePolesRoute
  BdeIndexRoute: typeof BdeIndexRoute
}

const BdeRouteChildren: BdeRouteChildren = {
  BdeAssociationRoute: BdeAssociationRoute,
  BdeEquipeRoute: BdeEquipeRoute,
  BdePolesRoute: BdePolesRoute,
  BdeIndexRoute: BdeIndexRoute,
}

const BdeRouteWithChildren = BdeRoute._addFileChildren(BdeRouteChildren)

interface BureauRouteChildren {
  BureauDossierIdRoute: typeof BureauDossierIdRoute
  BureauIndexRoute: typeof BureauIndexRoute
}

const BureauRouteChildren: BureauRouteChildren = {
  BureauDossierIdRoute: BureauDossierIdRoute,
  BureauIndexRoute: BureauIndexRoute,
}

const BureauRouteWithChildren =
  BureauRoute._addFileChildren(BureauRouteChildren)

interface EvenementsRouteChildren {
  EvenementsEventIdRoute: typeof EvenementsEventIdRoute
  EvenementsIndexRoute: typeof EvenementsIndexRoute
}

const EvenementsRouteChildren: EvenementsRouteChildren = {
  EvenementsEventIdRoute: EvenementsEventIdRoute,
  EvenementsIndexRoute: EvenementsIndexRoute,
}

const EvenementsRouteWithChildren = EvenementsRoute._addFileChildren(
  EvenementsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  AdhererRoute: AdhererRoute,
  BdeRoute: BdeRouteWithChildren,
  BoutiqueRoute: BoutiqueRoute,
  BureauRoute: BureauRouteWithChildren,
  ConditionsVenteRoute: ConditionsVenteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  EspaceRoute: EspaceRoute,
  EvenementsRoute: EvenementsRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RemboursementsRoute: RemboursementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
