/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdhererRouteImport } from './routes/adherer'
import { Route as BdeRouteImport } from './routes/bde'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as BdeIndexRouteImport } from './routes/bde.index'
import { Route as BdeAssociationRouteImport } from './routes/bde.association'
import { Route as BdeEquipeRouteImport } from './routes/bde.equipe'
import { Route as EvenementsIndexRouteImport } from './routes/evenements.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhererRoute = AdhererRouteImport.update({
  id: '/adherer',
  path: '/adherer',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeRoute = BdeRouteImport.update({
  id: '/bde',
  path: '/bde',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const BdeIndexRoute = BdeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BdeRoute,
} as any)
const BdeAssociationRoute = BdeAssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => BdeRoute,
} as any)
const BdeEquipeRoute = BdeEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => BdeRoute,
} as any)
const EvenementsIndexRoute = EvenementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvenementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adherer': typeof AdhererRoute
  '/bde': typeof BdeRouteWithChildren
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/bde/association': typeof BdeAssociationRoute
  '/bde/equipe': typeof BdeEquipeRoute
  '/bde/': typeof BdeIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adherer': typeof AdhererRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/bde/association': typeof BdeAssociationRoute
  '/bde/equipe': typeof BdeEquipeRoute
  '/bde': typeof BdeIndexRoute
  '/evenements': typeof EvenementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adherer': typeof AdhererRoute
  '/bde': typeof BdeRouteWithChildren
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRouteWithChildren
  '/mentions-legales': typeof MentionsLegalesRoute
  '/bde/association': typeof BdeAssociationRoute
  '/bde/equipe': typeof BdeEquipeRoute
  '/bde/': typeof BdeIndexRoute
  '/evenements/': typeof EvenementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adherer'
    | '/bde'
    | '/contact'
    | '/evenements'
    | '/mentions-legales'
    | '/bde/association'
    | '/bde/equipe'
    | '/bde/'
    | '/evenements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adherer'
    | '/contact'
    | '/mentions-legales'
    | '/bde/association'
    | '/bde/equipe'
    | '/bde'
    | '/evenements'
  id:
    | '__root__'
    | '/'
    | '/adherer'
    | '/bde'
    | '/contact'
    | '/evenements'
    | '/mentions-legales'
    | '/bde/association'
    | '/bde/equipe'
    | '/bde/'
    | '/evenements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdhererRoute: typeof AdhererRoute
  BdeRoute: typeof BdeRouteWithChildren
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRouteWithChildren
  MentionsLegalesRoute: typeof MentionsLegalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adherer': {
      id: '/adherer'
      path: '/adherer'
      fullPath: '/adherer'
      preLoaderRoute: typeof AdhererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde': {
      id: '/bde'
      path: '/bde'
      fullPath: '/bde'
      preLoaderRoute: typeof BdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bde/': {
      id: '/bde/'
      path: '/'
      fullPath: '/bde/'
      preLoaderRoute: typeof BdeIndexRouteImport
      parentRoute: typeof BdeRoute
    }
    '/bde/association': {
      id: '/bde/association'
      path: '/association'
      fullPath: '/bde/association'
      preLoaderRoute: typeof BdeAssociationRouteImport
      parentRoute: typeof BdeRoute
    }
    '/bde/equipe': {
      id: '/bde/equipe'
      path: '/equipe'
      fullPath: '/bde/equipe'
      preLoaderRoute: typeof BdeEquipeRouteImport
      parentRoute: typeof BdeRoute
    }
    '/evenements/': {
      id: '/evenements/'
      path: '/'
      fullPath: '/evenements/'
      preLoaderRoute: typeof EvenementsIndexRouteImport
      parentRoute: typeof EvenementsRoute
    }
  }
}

interface BdeRouteChildren {
  BdeAssociationRoute: typeof BdeAssociationRoute
  BdeEquipeRoute: typeof BdeEquipeRoute
  BdeIndexRoute: typeof BdeIndexRoute
}

const BdeRouteChildren: BdeRouteChildren = {
  BdeAssociationRoute: BdeAssociationRoute,
  BdeEquipeRoute: BdeEquipeRoute,
  BdeIndexRoute: BdeIndexRoute,
}

const BdeRouteWithChildren = BdeRoute._addFileChildren(BdeRouteChildren)

interface EvenementsRouteChildren {
  EvenementsIndexRoute: typeof EvenementsIndexRoute
}

const EvenementsRouteChildren: EvenementsRouteChildren = {
  EvenementsIndexRoute: EvenementsIndexRoute,
}

const EvenementsRouteWithChildren = EvenementsRoute._addFileChildren(
  EvenementsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdhererRoute: AdhererRoute,
  BdeRoute: BdeRouteWithChildren,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRouteWithChildren,
  MentionsLegalesRoute: MentionsLegalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
